version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: containers/nginx/nginx.dockerfile
      args:
        - USERID=${USERID:-1000}
        - GROUPID=${GROUPID:-1000}
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - ./containers/nginx/log:/var/log/nginx
      - ./containers/nginx/conf:/etc/nginx/conf.d
      - ./containers/nginx/certs:/etc/nginx/certs
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: containers/php/php.dockerfile
      args:
        - USERID=${USERID:-1000}
        - GROUPID=${GROUPID:-1000}
    volumes:
        - .:/var/www/html
        - ./containers/php/conf:/etc/php/conf.d
    depends_on:
        - redis
        - composer
#        - assets

  assets:
    image: node:current-alpine
    volumes:
      - ./:/var/www/html
    command: ['/bin/sh', '-c', 'npm install & npm run build ']
    working_dir: /var/www/html

  composer:
    image: composer:2.3
    volumes:
      - ./:/var/www/html
    command: ['/bin/sh', '-c', 'composer install --no-dev --optimize-autoloader']
    working_dir: /var/www/html

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6380:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - ./containers/redis/data:/data
