name: Dev deployment

on:
  workflow_dispatch:
  # push:
  # branches:
  #   - main

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 13.211.142.1
          port: 22
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          debug: true
          script: "sudo chmod +x ~/market/.scripts/deploy.sh; bash ~/market/.scripts/deploy.sh"
