name: Dev deployment

on:
  workflow_dispatch:
  # push:
  # branches:
  #   - main

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
      - uses: actions/checkout@v2
        env:
          PRIVATE_KEY: ${{ secrets.DEV_PRIVATE_KEY }}
          HOSTNAME: ${{secrets.DEV_HOST}}
          USER_NAME: ${{secrets.DEV_USER_NAME}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
              # Now we have got the access of EC2 and we will start the deploy .
              bash ~/market/.scripts/deploy.sh
              '
