name: Dev deployment

on:
  workflow_dispatch:
  # push:
  # branches:
  #   - main

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.DEV_HOST }}
          port: 22
          username: ${{ secrets.DEV_USER_NAME }}
          key: ${{ secrets.DEV_PRIVATE_KEY }}
          debug: true
          script: "cd ~/market; docker-compose down; git pull origin main;  docker-compose up -d; docker-compose run php php artisan migrate;"
