name: Dev deployment

on:
  workflow_dispatch:
  # push:
  # branches:
  #   - main

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEV_HOST }}
          port: 22
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          script: "cd /var/www/html && git pull origin main && docker-compose down && docker-compose up -d"
